# -*- coding: utf-8 -*-
"""LoanTap: Logisstic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1moicfsm4rXWi5ND5yXAHjzTGgcuT6XEo
"""

# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

# Global plot settings
sns.set_theme(style='whitegrid', palette='Set2', font_scale=1.05)
plt.rcParams.update({
    'figure.dpi': 110,
    'axes.titlesize': 13,
    'axes.titleweight': 'bold',
    'axes.labelsize': 11,
    'xtick.labelsize': 9,
    'ytick.labelsize':9
})

pd.set_option('display.max_columns', 40)
pd.set_option('display.float_format', '{:.3f}'.format)

"""# **Load Dataset**"""

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/logistic_regression.csv')

print(f"  Rows    : {df.shape[0]:,}")
print(f"  Columns : {df.shape[1]}")
print(f"\n➡️ First 3 rows preview:")
display(df.head(3))

"""## **Problem Statement:**
- LoanTap is a fintech platform that delivers customized, instant loan products to millennials and salaried professionals - targetting a segment traditionally underserved by legacy banking.

### **Business Problem:**
Loan tap needs to automate underwriting layer for persona loand that:
  
  (a) Decides WHETHER to extend credit to an applicant.
  
  (b) Recommends WHAT repayment terms (amount, tenure) are appropriate given the applicant's risk profile.

### Two competing business risk exits:
  

*   1. Risk - 1 --- NPA (Non-Performing Assest):
    - if a bad borrower is approved -> loan is not repaid -> capital lost
    - this is a direct, permant financial loss on the balance sheet.



*   2. Riskt -- 2 Missed Revenue (False Rejection):
      - If a good borrower is rejected -> interest income is foregone.
      - This is an oportunity cost - no capital is lot, only potential gain.


* Since Risk 1 > Risk 2 in severity, the model must prioritize catching real defaulters over perfect precision.

* MACHINE LEARNING FRAMING:
    
    Type      : Binary Classification
    
    Target    : loan_status

    'Fully Paid'  → 0  (non-default)

    'Charged Off' → 1  (default)
    
    
    Algorithm : Logistic Regression (interpretable, auditable, industry-standard)


---



---


* DATASET:
    
    Source  : LoanTap internal lending records
   
    Rows    : 396,030 loan applications
   
    Columns : 27 attributes covering borrower profile, loan characteristics credit history, and repayment behavior.


---


---



* EVALUATION FOCUS:
    Primary metric  → Recall  (minimize missed defaulters / NPAs)
  
    Secondary metric→ ROC-AUC (overall discriminatory power across thresholds)
  
    Tertiary metric → Precision (balance with business growth goals)

### **Structure and characteristics of the dataset**
"""

# shape
print(f"\n► SHAPE")
print(f"  Rows    : {df.shape[0]:,}")
print(f"  Columns : {df.shape[1]}")
print(f"  Total data points: {df.shape[0] * df.shape[1]:,}")

# Column names and raw datatypes:
print(f"  {'Column':<30} {'Dtype':<15} {'Non-Null Count'}")
for col in df.columns:
  non_null = df[col].notna().sum()
  print(f" {col:<30} {str(df[col].dtype):<15} {non_null:,}")

# Classify columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
object_cols = df.select_dtypes(include=['object']).columns.tolist()

print(f"\n► COLUMN CLASSIFICATION:")
print(f"  Numeric columns  ({len(numeric_cols)}): {numeric_cols}")
print(f"  Object  columns  ({len(object_cols)}) : {object_cols}")

"""### **Insights:**
- Most numeric columns are already float64.
- Several columns appear numeric bur encode categories.
  -  'term' contains '36 month' / '60 months' -> category or int.
  - 'emp_length' contains '10+ years' strings -> needs to extraction to int.
- Columns like 'issue_d' and earliest_cr_line' are date string -> need conversion to extract year/month for time-series features.
- 'address' is free-text -> useful only for extracting strate abbreviation
"""

# Categorical columns to 'category' dtypes.

cat_cols_to_convert = [
    'term',               # '36 months' or '60 months'
    'grade',              # A, B, C, D, E, F, G
    'sub_grade',          # A1 … G5
    'emp_length',         # '< 1 year', '1 year', …, '10+ years'
    'home_ownership',     # RENT, MORTGAGE, OWN, OTHER, NONE
    'verification_status',# Not Verified, Source Verified, Verified
    'loan_status',        # Fully Paid, Charged Off  ← TARGET
    'purpose',            # debt_consolidation, credit_card, …
    'initial_list_status',# w (whole) or f (fractional)
    'application_type',   # INDIVIDUAL or JOINT
]

# Only convert columns that actually exist in the dataframe
cat_cols_to_convert = [c for c in cat_cols_to_convert if c in df.columns]

print(f"\n  Converting {len(cat_cols_to_convert)} columns to 'category'...\n")
for col in cat_cols_to_convert:
    before_dtype = str(df[col].dtype)
    df[col] = df[col].astype('category')
    unique_vals = df[col].nunique()
    print(f"  ✅ {col:<25} {before_dtype:<12} → category  "
          f"({unique_vals} unique values)")

print(f"\n► Current dtypes after conversion:")
print(df.dtypes)

"""### **Missing value detection**"""

missing_count = df.isnull().sum()
missing_pct = (missing_count / len(df) * 100).round(2)
missing_df = pd.DataFrame({
    'Column'        : missing_count.index,
    'Missing Count' : missing_count.values,
    'Missing %'     : missing_pct.values,
    'Dtypes'        : df.dtypes.values
}).query('`Missing Count` > 0').sort_values('Missing %', ascending=False)

print(f"\n Columns WITH missing values ({len(missing_df)} found):\n")
display(missing_df.reset_index(drop=True))

print(f"\n  Columns with ZERO missing values: "f"{(missing_count == 0).sum()} columns are complete.")

"""### **Visual: Missing value bar chat:-**"""

fig, ax = plt.subplots(figsize= (10,5))
colors = ['#E53935' if p > 5 else '#FB8C00' if p > 1 else '#43A047'
            for p in missing_df['Missing %']]

bars = ax.barh(missing_df['Column'], missing_df['Missing %'], color=colors, edgecolor='black', height=0.6)

# Add % labels on bars
for bar, pct in zip(bars, missing_df['Missing %']):
  ax.text(bar.get_width() + 0.1, bar.get_y() + bar.get_height()/2, f'{pct:.1f}%', va='center', fontsize=9)

ax.set_xlabel('Missing Percentage (%)')
ax.set_title('Missing Values by Column\n(Red > 5%  | Orange 1-5%  | Green <1%)',fontweight='bold')
ax.axvline(5, color='red', linestyle = '--', lw=1.2, alpha=0.7,label='5% line')
ax.legend(fontsize=9)
ax.invert_yaxis() # highest missing at top
plt.tight_layout()
plt.savefig('missing_values.png', dpi=100, bbox_inches='tight')
plt.show()

"""### **Missing Values insights**
- mort_acc 9.5% missing values -> Borrower has no mortgage (0 = absent).
- emp_title 5.8% missing values -> Not provided by borrowerr voluntarily.
- emp_lenght 4.5 % missing values -> Self-employed / recent graduates skip
- title 0.4% missing values -> Free-text field.
- pub_rec_bankrupties 0.1 % missing values -> No record = 0 bankruptcies.
- revol_util 0.07% missing values -> Missing credit utilization info.

*NOTE: WE DO NOT TREAT MISSING VALUES HERE. Treatment happens in Preprocessing part.*

### **Statistical Summary:**
"""

# Numeric summary
print("\n► NUMERIC COLUMNS – Descriptive Statistics:")
display(df.describe().T.style.format('{:.2f}'))

# Categorical summary
print("\n► CATEGORICAL COLUMNS – Value Counts Summary:")
cat_summary = []

for col in cat_cols_to_convert:
  if col in df.columns:
    top_val = df[col].value_counts().index[0]
    top_freq = df[col].value_counts().iloc[0]
    top_pct = top_freq / len(df) * 100
    cat_summary.append({
        'Column': col,
        'Unique Values': df[col].nunique(),
        'Top Value' : str(top_val),
        'Top Count' : top_freq,
        'Top %': f'{top_pct:.1f}%'
    })

display(pd.DataFrame(cat_summary))

"""### **STATISTICAL SUMMARY INSIGHTS:**

1. LOAN AMOUNT (loan_amnt):

    Min=$500, Max=$40,000, Mean≈$14,100, Median≈$12,000

    → Most loans are $5K–$20K. Higher amounts less common.

    → 75th percentile is $20,000 — large loans are the minority.

2. INTEREST RATE (int_rate):

    Range: 5.3% – 30.9%, Mean≈13.2%

    → Relatively normal distribution. High rates (>20%) are rare but exist.

    → High int_rate is LoanTap's own signal of perceived borrower risk.

3.  ANNUAL INCOME (annual_inc):


    Mean≈$74,200 but Std≈$61,000 — huge variability.

    Max can exceed $8M — extreme outliers exist.


4.  INSTALLMENT:


    Mean≈$431, which multiplied by mean term gives total loan cost.

    → Highly correlated with loan_amnt (expected).

5. DTI (Debt-to-Income):

    Mean≈17.4, Max≈999 (data quality issue — needs capping).

    → Values >50 are unrealistic for salaried borrowers.

6. PUB_REC, PUB_REC_BANKRUPTCIES:

    Mean close to 0; most borrowers have clean records

7. TARGET VARIABLE (loan_status):

    Top value = 'Fully Paid' (~80.4%)

    → Imbalanced dataset — requires class_weight='balanced' in model.

### **UNIVARIATE ANALYSIS – Continuous Variables**
"""

from matplotlib import transforms
from IPython.core.pylabtools import figsize
# All continuous/numeric columns of interest.
continuous_cols = [
    'loan_amnt', 'int_rate', 'installment', 'annual_inc',
    'dti', 'open_acc', 'pub_rec', 'revol_bal',
    'revol_util', 'total_acc', 'mort_acc', 'pub_rec_bankruptcies'
]

continuous_cols = [c for c in continuous_cols if c in df.columns]

# Plot: Histogram with kde for all continous variables:

fig, axes = plt.subplots(4,3, figsize=(20,18))
fig.suptitle('Univariate Distributions - Continuous Variables\n(Histogram + KDE overlay)', fontsize=15, fontweight='bold', y=1.01)
axes = axes.flatten()

palette_colors = sns.color_palette('Set2', len(continuous_cols))

for i, col in enumerate(continuous_cols):
  data = df[col].dropna()
  ax   = axes[i]


  # Histogram
  ax.hist(data, bins=50, color=palette_colors[i],edgecolor='white', alpha=0.80,density=True)

  #KDE overlay
  try:
    from scipy.stats import gaussian_kde
    kde = gaussian_kde(data)
    x_range = np.linspace(data.min(), data.max(),300)
    ax.plot(x_range,kde(x_range), color='black',lw=1.8)
  except Exception:
    pass

  # Stats annotations:
  skew_val = data.skew()
  mean_val = data.mean()
  ax.axvline(mean_val, color='red', linestyle='--', lw=1.5, label='Mean')
  ax.axvline(data.median(),color='blue', linestyle='--', lw=1.5,label="Median")

  ax.set_title(col, fontsize=12, fontweight='bold')
  ax.set_xlabel('')
  ax.text(0.97,0.95, f'Skew: {skew_val:.2f}', transform=ax.transAxes, ha='right', va='top',fontsize=9, color='darkred',bbox=dict(boxstyle='round,pad=0.2', facecolor='lightyellow', alpha=0.8))
  if i ==0:
    ax.legend(fontsize=8)

# Hide unused subplots:
for j in range(i + 1, len(axes)):
  axes[j].set_visible(False)


plt.tight_layout()
plt.savefig('univariate_continuous.png',dpi=100,bbox_inches='tight')
plt.show()

"""1. loan_amnt (Loan Amount):

     → Right-skewed (skew > 1). Peak at $10K–$15K. Tail extends to $40K.

     → Most borrowers request moderate amounts. Very large loans are rare.

     → OUTLIER NOTE: Values above $35K are rare but legitimate (max=$40K).


  2. int_rate (Interest Rate):
  
     → Roughly bell-shaped. Center ~12–14%. Range: 5.3%–30.9%.
  
     → Slight right skew. Rates >22% represent the riskiest borrowers.
  
     → This is LoanTap's own risk rating — highly informative for the model.


  3. installment (Monthly Payment):

     → Distribution mirrors loan_amnt (correlation = 0.95).

     → Including both in the model introduces multicollinearity.

     → One must be dropped during preprocessing.


  4. annual_inc (Annual Income):

     → Extremely right-skewed. Most incomes fall between $40K–$100K.

     → Extreme values (>$300K) are likely real but distort statistics.

     → REQUIRES CAPPING at 99th percentile before modeling.


  5. dti (Debt-to-Income Ratio):

     → Near-normal shape, center ~15–20. Right tail extends to ~40+.

     → Very high DTI (>40) suggests borrower is over-leveraged.

     → Extreme values (DTI=999) are data quality errors → cap needed.


  6. open_acc (Open Credit Lines):

     → Right-skewed integer. Mode around 8–10.

     → Borrowers with 20+ open lines may be over-leveraged.


  7. pub_rec (Public Derogatory Records):

     → SEVERELY right-skewed. ~85% of borrowers have pub_rec = 0.

     → Creating a binary flag (0 vs 1+) is more useful than raw value.


  8. revol_bal (Revolving Balance):

     → Heavily right-skewed. Most have $0–$20K balance.

     → Tail extends to $1M+. Outlier capping essential.


  9. revol_util (Revolving Utilization):

     → Approximately uniform with slight right skew. Range 0%–150%+.

     → Values >100% indicate data quality issue (balance exceeds limit).

     → High utilization (>80%) is a strong default signal.


  10. total_acc (Total Credit Lines Ever):

      → Roughly normal-ish, range 2–162. Center ~25.

      → Proxy for credit experience; more lines = older credit history.


  11. mort_acc (Mortgage Accounts):

      → Right-skewed. Most have 0–2 mortgages.

      → Having a mortgage indicates creditworthy status (bank approved them).


  12. pub_rec_bankruptcies:

      → Almost all values are 0. Extreme right skew.

      → Binary flag (any bankruptcy vs none) is the right transformation.

### **Univariate - Continous Variables (Boxplots)**
"""

# Boxplots to highlight outliers:
fig, axes = plt.subplots(3,4,figsize=(20,14))
fig.suptitle('Boxplots - Outliers Detection for Continuous Variables',fontsize=15,fontweight='bold',y=1.01)
axes = axes.flatten()

for i, col in enumerate(continuous_cols):
  data = df[col].dropna()
  ax = axes[i]

  bp = ax.boxplot(data, vert=True, patch_artist=True,
                  boxprops=dict(facecolor=palette_colors[i], alpha=0.7),
                  medianprops=dict(color='red',linewidth=2),
                  whiskerprops=dict(linewidth=1.5),
                  capprops=dict(linewidth=1.5),
                  flierprops=dict(marker='o',markerfacecolor='gray',markersize=2,alpha=0.3))

  # IQR and outlier bounds
  Q1 = data.quantile(0.25)
  Q3 = data.quantile(0.75)
  IQR = Q3 - Q1
  lower = Q1 - 1.5 * IQR
  upper = Q3 + 1.5 * IQR
  n_outilers = ((data < lower) | (data > upper)).sum()

  ax.set_title(col, fontsize=11, fontweight='bold')
  ax.set_xlabel('')
  ax.text(0.97,0.97,
          f'Outilers: {n_outilers:,}\n({n_outilers/len(data)*100:.1f}%)',
          transform=ax.transAxes, ha='right', va='top',fontsize=8,color='darkred',
          bbox=dict(boxstyle='round,pad=0.2',facecolor='lightyellow',alpha=0.8))

for j in range(i + 1, len(axes)):
  axes[j].set_visible(False)

plt.tight_layout()
plt.savefig('univariate_continuous_boxplots.png',dpi=100,bbox_inches='tight')
plt.show()

"""• annual_inc  : Largest outlier problem. Values extend far beyond IQR.
  Top 1% earns >$300K — these dominate the boxplot whiskers.

  • revol_bal   : Similar extreme right outliers.
  
  • loan_amnt   : Mild outliers at the top end (~$35K–$40K). Acceptable range.
  
  • int_rate    : No extreme outliers. Clean, bounded distribution.
  
  • dti         : Some extreme values (>60) suggest data entry errors.
  
  • pub_rec     : Technically every value >0 is an outlier by IQR definition
                  due to the extreme concentration at 0.
  
  • revol_util  : Values >100 are impossible (utilization cannot exceed 100%)
                  → These should be capped at 100.
  
  • total_acc   : A few borrowers have 100+ accounts — plausible but extreme.

### UNIVARIATE ANALYSIS - Categorical Variables
"""

cat_plot_cols = ['loan_status', 'grade', 'home_ownership',
                 'verification_status', 'purpose', 'term',
                 'initial_list_status', 'application_type', 'emp_length']

cat_plot_cols = [c for c in cat_plot_cols if c in df.columns]

fig, axes = plt.subplots(3,3,figsize=(22,18))
fig.suptitle('Univariate Analysis - Categorical Variables\n(Count plots with percentage labels)',fontsize=15,fontweight='bold',y=1.01)
axes = axes.flatten()

for i, col in enumerate(cat_plot_cols):
  ax = axes[i]
  order = df[col].value_counts().index.tolist()

  sns.countplot(data=df, x=col, order=order, ax=ax, palette='Set2',edgecolor='black', linewidth=0.5)

  ax.set_title(col, fontsize=12, fontweight='bold')
  ax.set_xlabel('')
  ax.tick_params(axis='x',rotation=35)

  # Add percentage labels above each bar
  total = len(df)
  for p in ax.patches:
    height = p.get_height()
    if height > 0:
      ax.annotate(f'{height/total*100:.1f}%',
                  xy=(p.get_x() + p.get_width() / 2,height),
                  xytext=(0,4), textcoords='offset points',
                  ha='center',va='bottom',fontsize=8,fontweight='bold')

for j in range(i+1, len(axes)):
  axes[j].set_visible(False)

plt.tight_layout()
plt.savefig('univariate_categorical.png',dpi=110,bbox_inches='tight')
plt.show()

"""### **Insights:**
1. loan_status (TARGET):

→ 80.4% Fully Paid vs 19.6% Charged Off.

→ Significant CLASS IMBALANCE — 4:1 ratio.

→ Naive model predicting all "Fully Paid" achieves 80% accuracy but
  0% recall for defaulters. Must use class_weight='balanced'.


2. grade (A → G):

→ Grade B is the most common (~30%), followed by C (~22%).

→ Grade A (~17%) is the safest; Grade G (<1%) is the riskiest.

→ Distribution is approximately bell-shaped around BC.


3. home_ownership:

→ MORTGAGE dominates (47.8%), then RENT (39.5%), OWN (12.3%).

→ 'ANY', 'OTHER', 'NONE' are negligible (<0.1%) — can be grouped.

→ MORTGAGE holders may have greater financial stability.


4. verification_status:

→ ~45% Not Verified — LoanTap extends credit without income proof.

→ ~32% Source Verified, ~23% Verified.

→ Counter-intuitively, Verified borrowers sometimes default more
  (because verification is triggered for borderline cases).


5. purpose:

→ debt_consolidation dominates (~47%) — people consolidating debt.

→ credit_card (~12%), home_improvement (~7%) follow.

→ 'small_business' has higher default rates despite low volume.


6. term:

→ 36-month (72.8%) vs 60-month (27.2%).

→ 60-month borrowers carry higher default risk (longer exposure).


7. initial_list_status:

→ 'w' (whole loans) = 56%, 'f' (fractional) = 44%.

→ Whole loans are sold as single units; fractional are crowdfunded.

→ May have differing risk profiles due to selection bias.


8. application_type:

→ 98.7% INDIVIDUAL, 1.3% JOINT.

→ Joint applications are too rare to have model impact.

→ Can be kept as binary indicator (1 = JOINT).


9. emp_length:

→ '10+ years' is the modal category (~33%) — many long-tenured borrowers.

→ '< 1 year' is second most common (~11%) — recent entrants.

→ Bimodal shape: peak at <1 yr (new) and 10+ yrs (senior professionals).

→ Convert to numeric (0–10) for modeling.

## **Bivariate Analysis - Target Vs Predictors**
"""

# Grade vs Loan Status
fig, axes = plt.subplots(1,2,figsize=(18,6))
fig.suptitle('Bivariate: Grade vs Loan Status',fontsize=14,fontweight='bold')

# Count Plot
grade_status = df.groupby(['grade','loan_status'], observed=True).size().unstack(fill_value=0)
grade_status.plot(kind='bar',ax=axes[0],color=['#43A047', '#E53935'], edgecolor='black', width=0.7)
axes[0].set_title('Count of Loans by Grade & Status')
axes[0].set_xlabel('Grade')
axes[0].tick_params(axis='x',rotation=0)
axes[0].legend(title='Loan Status',fontsize=9)

# Stacked % plot
grade_pct = grade_status.div(grade_status.sum(axis=1), axis=0) * 100
grade_pct.plot(kind='bar',stacked=True,ax=axes[1],
               color=['#43A047', '#E53935'], edgecolor='black',width=0.7)
axes[1].set_title('Default Rate (%) by Grade')
axes[1].set_xlabel('Grade')
axes[1].tick_params(axis='x', rotation=0)
axes[1].set_ylabel('Percentage (%)')
axes[1].legend(title='Loan Status', fontsize=9)

# Add default % labels
charged_pct = grade_pct.get('Charged Off', grade_pct.iloc[:, -1])
for j, (grade, pct) in enumerate(charged_pct.items()):
    axes[1].text(j, grade_pct.iloc[j, 0] + pct / 2,
                 f'{pct:.0f}%', ha='center', va='center',
                 fontsize=9, fontweight='bold', color='white')

plt.tight_layout()
plt.savefig('bivariate_grade_status.png', dpi=110, bbox_inches='tight')
plt.show()

"""### **GRADE vs LOAN STATUS:**

• Clear monotonic trend: default rate increases from Grade A to Grade G.

• Grade A: ~6% default rate  →  Grade G: ~37% default rate.

• Grade is LoanTap's internal risk score — it works well as a predictor.

• Grades F and G have very small volumes but very high default rates.

• INSIGHT: Grade alone is not sufficient (sub_grade adds finer resolution).


"""

# Interest Rate by Loan Status;

fig, axes = plt.subplots(1,2,figsize=(16,6))
fig.suptitle('Bivariate: Interest Rate vs Loan Status',fontsize=14,fontweight='bold')

# KDE / Histogram overlay

for label, grp in df.groupby('loan_status',observed=True):
  axes[0].hist(grp['int_rate'].dropna(),bins=50,alpha=0.55,
               label=str(label),density=True,edgecolor='white')
axes[0].set_title('Interest Rate Distribution by Loan Status')
axes[0].set_xlabel('Interest Rate (%)')
axes[0].set_ylabel('Density')
axes[0].legend(fontsize=9)

# Boxplot
df.boxplot(column='int_rate', by='loan_status', ax=axes[1],
           showfliers=True,
           patch_artist=True,
           boxprops=dict(facecolor='#90CAF9',alpha=0.7),
           medianprops=dict(color='red', linewidth=2))
axes[1].set_title('Interest Rate Distribution by Loan Status')
axes[1].set_xlabel('Loan Status')
axes[1].set_ylabel('Interest Rate (%)')
plt.sca(axes[1])
plt.title('Interest Rate by Loan Status')
plt.suptitle('')

plt.tight_layout()
plt.savefig('bivariate_int_rate_status.png', dpi=110, bbox_inches='tight')
plt.show()

# Mean int_rate by status
print(df.groupby('loan_status',observed=True)['int_rate'].agg(['mean','median']).round(2))

"""### **INTEREST RATE vs LOAN STATUS:**
• Charged Off loans have mean int_rate ≈ 14.5% vs ~12.3% for Fully Paid.
  
• The distributions overlap significantly — int_rate alone cannot separate the classes, but it contributes meaningfully.

• Boxplot shows Charged Off has a higher median AND wider spread.

• INSIGHT: int_rate is LoanTap's own assessment of risk → self-fulfilling. Riskier borrowers pay more → they are more financially stressed → they default.

• This is the STRONGEST individual predictor in our logistic regression.

### **Loan Amount by Loan Status:**
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Bivariate: Loan Amount vs Loan Status', fontsize=14, fontweight='bold')

for label, grp in df.groupby('loan_status', observed=True):
    axes[0].hist(grp['loan_amnt'].dropna(), bins=40, alpha=0.55,
                 label=str(label), density=True, edgecolor='white')
axes[0].set_title('Loan Amount Distribution by Loan Status')
axes[0].set_xlabel('Loan Amount ($)')
axes[0].set_ylabel('Density')
axes[0].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}K'))
axes[0].legend(fontsize=9)

df.boxplot(column='loan_amnt', by='loan_status', ax=axes[1],
           showfliers=True, patch_artist=True,
           boxprops=dict(facecolor='#CE93D8', alpha=0.7),
           medianprops=dict(color='red', linewidth=2))
axes[1].set_title('Loan Amount by Loan Status')
axes[1].set_xlabel('Loan Status')
plt.sca(axes[1]); plt.title('Loan Amount by Loan Status'); plt.suptitle('')

plt.tight_layout()
plt.savefig('bivariate_loanamnt_status.png', dpi=110, bbox_inches='tight')
plt.show()

print("  Mean loan amount by loan_status:")
print(df.groupby('loan_status', observed=True)['loan_amnt'].agg(['mean', 'median']).round(0))

"""### **LOAN AMOUNT vs LOAN STATUS:**
• Charged Off loans have slightly higher average loan amounts (~$15,400) vs Fully Paid (~$13,900) — moderate difference.

• Both distributions have similar shapes; amount alone is not a strong separator.

• INSIGHT: It's not just HOW MUCH was borrowed, but who borrowed it
(income, grade, utilization) that matters. Loan amount gains predictive
power only in combination with other features.

### **DTI by Loan Status:**
"""

fig, axes = plt.subplots(1, 2, figsize=(16,6))
fig.suptitle('Bivariate: DTI vs Loan Status', fontsize=14, fontweight='bold')

for label, grp in df.groupby('loan_status',observed=True):
  clean = grp['dti'].dropna()
  clean = clean[clean < 60]
  axes[0].hist(clean, bins=40, alpha = 0.55,
               label=str(label), density=True,edgecolor='white')
axes[0].set_title('DTI Distribution by Loan Status (capped at 60)')
axes[0].set_xlabel('DTI')
axes[0].legend(fontsize=9)

df[df['dti'] < 60].boxplot(column='dti', by='loan_status', ax=axes[1],
                           showfliers=False, patch_artist=True,
                           boxprops=dict(facecolor='#FFCC80', alpha=0.8),
                           medianprops=dict(color='red',linewidth=2))

axes[1].set_title('DTI Boxplot by Loan Status')
axes[1].set_xlabel('Loan Status')
plt.sca(axes[1]); plt.title('DTI by Loan Status'); plt.suptitle('')

plt.tight_layout()
plt.savefig('bivariate_dti_status.png', dpi=110, bbox_inches='tight')
plt.show()

"""### **DTI vs LOAN STATUS:**

• Charged Off borrowers have slightly higher mean DTI (~18.8) vs Fully Paid (~17.1).

• The difference is statistically meaningful despite visual overlap.

• DTI >35 is a red flag — most lenders have hard cutoffs around 43%.

• INSIGHT: DTI captures whether the borrower can afford monthly payments.

High DTI means most income goes to debt service → vulnerable to any shock.

### Annual Income by Loan Status:
"""

income_cap = df['annual_inc'].quantile(0.99)
df_cap = df[df['annual_inc'] < income_cap].copy()

fig, axes = plt.subplots(1, 2, figsize=(16,6))
fig.suptitle('Bivariate: Annual Income vs Loan Status', fontsize= 14,
             fontweight='bold')

for label, grp in df_cap.groupby('loan_status',observed=True):
  axes[0].hist(grp['annual_inc'].dropna(), bins=40, alpha=0.55,
               label=str(label),density=True, edgecolor='white')
axes[0].set_title('Annual Income Distribution by Loan Status')
axes[0].set_xlabel('Annual Income ($) ')
axes[0].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}K'))
axes[0].legend(fontsize=9)

df_cap.boxplot(column='annual_inc', by='loan_status', ax=axes[1],
               showfliers=False, patch_artist=True,
               boxprops=dict(facecolor='#80DEEA', alpha=0.8),
               medianprops=dict(color='red', linewidth=2))
axes[1].set_title('Income Boxplot by Loan Status')
axes[1].set_xlabel('Loan Status')
plt.sca(axes[1]); plt.title('Annual Income by Loan Status'); plt.suptitle('')

plt.tight_layout()
plt.savefig('bivariate_income_status.png',dpi=110, bbox_inches='tight')
plt.show()

print("  Mean annual income by loan_status:")
print(df.groupby('loan_status', observed=True)['annual_inc'].agg(['mean', 'median']).round(0))

"""### **ANNUAL INCOME vs LOAN STATUS:**

• Fully Paid borrowers have higher median income (~$62K vs ~$58K).

• The income difference is modest but consistent.

• Higher-income borrowers have more buffer to handle financial shocks.

• INSIGHT: Income alone is not sufficient. A high income with high debt
  (high DTI) still leads to defaults. Income must be used jointly with DTI.

### **Home Ownership vs Loan Status:**
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Bivariate: Home Ownership vs Loan Status', fontsize=14, fontweight='bold')

#Home owner count
ho_count = df.groupby(['home_ownership', 'loan_status'], observed=True).size().unstack(fill_value=0)
ho_pct = ho_count.div(ho_count.sum(axis=1), axis=0) * 100

ho_count.plot(kind='bar', ax=axes[0], color=['#43A047','#E53935'],
              edgecolor='black', width=0.7)
axes[0].set_title('Count by Home Owenership & Loan Status')
axes[0].tick_params(axis='x', rotation=0)
axes[0].legend(title='Status', fontsize=9)

ho_pct.plot(kind='bar', stacked=True, ax=axes[1],
            color=['#43A047', '#E53935'], edgecolor='black', width=0.7)
axes[1].set_title('Default Rate (%) by Home Ownership')
axes[1].tick_params(axis='x', rotation=20)
axes[1].set_ylabel('Percentage (%)')
axes[1].legend(title='Status', fontsize=9)

plt.tight_layout()
plt.savefig('bivariate_homeown_status.png', dpi=110, bbox_inches='tight')
plt.show()

print("  Default rate (%) by home_ownership:")
choff_col = [c for c in ho_pct.columns if 'Charged' in str(c)]
if choff_col:
    print(ho_pct[choff_col[0]].sort_values(ascending=False).round(1).to_string())

"""### **HOME OWNERSHIP vs LOAN STATUS:**

• 'OTHER' and 'ANY' categories have higher default rates (too rare to generalize).

• MORTGAGE holders have a slightly lower default rate vs RENT.

• OWN (outright homeowners) have the lowest default rate.

• INSIGHT: Owning property signals financial stability and acts as
  implicit collateral motivation to maintain creditworthiness.
"""

